apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ortelius
  namespace: ortelius
  finalizers:
    - resources-finalizer.argocd.argoproj.io # enabling cascading deletion
spec:
  project: pangarabbit
  source:
    repoURL: "https://ortelius.github.io/ortelius-charts/" # helm chart repository
    chart: ortelius # helm chart name
    targetRevision: 10.0.4407 # helm chart version - use latest available here
    # helm:
    #   parameters:
    #     - name: "commitID"
    #       value: "$ARGOCD_APP_REVISION"
  destination:
    server: "https://kubernetes.default.svc" # server where ortelius will be deployed
    namespace: ortelius # namespace where ortelius will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
